[package]
name = "lagoon_js"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lagoon_parser = { path = "../lagoon-parser" }
thiserror = "1.0"
colored = "2"